sudo: required
services:
  - docker

script:
  - docker build --tag myimage .
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker run myimage
  - kill %1

after_script:
  - docker images
